---
- package: name={{item}} state=installed
  with_items:
    - python3-scipy
    - python3-numpy
    - python3-pip

# Pygame install on ubuntu3
# http://askubuntu.com/a/825014

- package: name=ipython3-notebook state=installed
- package: name=spyder3 state=installed
- package: name=virtualenv state=installed

# tensorflow install for python 3
# http://askubuntu.com/a/772913

- include: roles/godeeper/tasks/common_pips.yml pipbin=pip3

