---
# TODO - not tested yet!
# bottom of:
# https://opensolitude.com/2015/05/26/building-docker-images-with-ansible.html
- name: Make a docker container from the godeeper ansible playbook
  hosts: localhost
#  become: true
  tasks:
    - name: create a unique temp container name
      set_fact:
        temp_container_name: ex3_build_{{lookup('pipe', 'date "+%Y%m%d%H%M%S"')}}

    - name: build site by running ansible in a docker container
      command: "docker run
        -v /tmp/site:/site
        -w /site
        --name={{temp_container_name}}
        ansible/ubuntu14.04-ansible:latest
        ansible-playbook godeeper.yml -c local"

    - name: create a docker image from the container
      command: "docker commit
        -c 'EXPOSE 80'
        -c 'CMD [\"nginx\", \"-g\", \"daemon off;\"]'
        {{temp_container_name}}
        built-by-ansible:ex3"
    - name: delete the container once the image has been successfully built
      command: docker rm -f -v {{temp_container_name}}

